// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AskAI sends audio to Gemini and returns an AI-generated answer (not a transcription).
 * @param {string} base64Audio
 * @param {string} mimeType
 * @returns {$CancellablePromise<string>}
 */
export function AskAI(base64Audio, mimeType) {
    return $Call.ByID(3851891320, base64Audio, mimeType);
}

/**
 * DisableCancelHotkey unregisters the Escape hotkey.
 * @returns {$CancellablePromise<void>}
 */
export function DisableCancelHotkey() {
    return $Call.ByID(1634357387);
}

/**
 * EnableCancelHotkey registers Escape as a global hotkey to cancel recording.
 * @returns {$CancellablePromise<void>}
 */
export function EnableCancelHotkey() {
    return $Call.ByID(2388360750);
}

/**
 * GetSettings returns current settings
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * HideAskWindow hides the ask/answer window.
 * @returns {$CancellablePromise<void>}
 */
export function HideAskWindow() {
    return $Call.ByID(2450570702);
}

/**
 * HideSettingsWindow closes the settings window
 * @returns {$CancellablePromise<void>}
 */
export function HideSettingsWindow() {
    return $Call.ByID(3159708740);
}

/**
 * HideWindow hides the floating widget (used by the − button)
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByID(542966029);
}

/**
 * PasteText writes text to clipboard and simulates Ctrl+V
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function PasteText(text) {
    return $Call.ByID(1951243735, text);
}

/**
 * SaveSettings persists settings to disk
 * @param {$models.Settings} s
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(s) {
    return $Call.ByID(1949631069, s);
}

/**
 * ShowAnswer displays the AI answer in the floating ask window.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function ShowAnswer(text) {
    return $Call.ByID(3513394294, text);
}

/**
 * ShowSettingsWindow opens the settings window
 * @returns {$CancellablePromise<void>}
 */
export function ShowSettingsWindow() {
    return $Call.ByID(2596981913);
}

/**
 * TranscribeAudio sends audio base64 to Gemini API and returns transcription
 * @param {string} base64Audio
 * @param {string} mimeType
 * @returns {$CancellablePromise<string>}
 */
export function TranscribeAudio(base64Audio, mimeType) {
    return $Call.ByID(3180610808, base64Audio, mimeType);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
