// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DictationProfile defines a named transcription mode with a custom prompt.
 */
export class DictationProfile {
    /**
     * Creates a new DictationProfile instance.
     * @param {Partial<DictationProfile>} [$$source = {}] - The source object to create the DictationProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DictationProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DictationProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DictationProfile(/** @type {Partial<DictationProfile>} */($$parsedSource));
    }
}

/**
 * HotkeyConfig stores a global keyboard shortcut definition.
 */
export class HotkeyConfig {
    /**
     * Creates a new HotkeyConfig instance.
     * @param {Partial<HotkeyConfig>} [$$source = {}] - The source object to create the HotkeyConfig.
     */
    constructor($$source = {}) {
        if (!("modifiers" in $$source)) {
            /**
             * Win32 MOD_* flags (excl. MOD_NOREPEAT)
             * @member
             * @type {number}
             */
            this["modifiers"] = 0;
        }
        if (!("vkey" in $$source)) {
            /**
             * Win32 virtual-key code
             * @member
             * @type {number}
             */
            this["vkey"] = 0;
        }
        if (!("display" in $$source)) {
            /**
             * Human-readable label, e.g. "Ctrl+Space"
             * @member
             * @type {string}
             */
            this["display"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HotkeyConfig(/** @type {Partial<HotkeyConfig>} */($$parsedSource));
    }
}

/**
 * Settings holds the app configuration.
 * APIKey is NOT persisted in the JSON file; it lives in the OS keyring.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Only in memory / transmitted to UI; never written to disk
             * @member
             * @type {string | undefined}
             */
            this["api_key"] = undefined;
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("hotkey" in $$source)) {
            /**
             * @member
             * @type {HotkeyConfig}
             */
            this["hotkey"] = (new HotkeyConfig());
        }
        if (!("opacity" in $$source)) {
            /**
             * Widget window opacity: 10–100 (percent)
             * @member
             * @type {number}
             */
            this["opacity"] = 0;
        }
        if (!("profiles" in $$source)) {
            /**
             * @member
             * @type {DictationProfile[]}
             */
            this["profiles"] = [];
        }
        if (!("active_profile_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["active_profile_id"] = "";
        }
        if (!("ask_hotkey" in $$source)) {
            /**
             * @member
             * @type {HotkeyConfig}
             */
            this["ask_hotkey"] = (new HotkeyConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hotkey" in $$parsedSource) {
            $$parsedSource["hotkey"] = $$createField2_0($$parsedSource["hotkey"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField4_0($$parsedSource["profiles"]);
        }
        if ("ask_hotkey" in $$parsedSource) {
            $$parsedSource["ask_hotkey"] = $$createField6_0($$parsedSource["ask_hotkey"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = HotkeyConfig.createFrom;
const $$createType1 = DictationProfile.createFrom;
const $$createType2 = $Create.Array($$createType1);
